app:
  name: quarkus-app-rhdh-2
  namespace: cmoullia
  virtualMachineName: quarkus-dev
  virtualMachineNamespace: cmoullia
  cluster:    #

build:
  native: false

git:
  branch: main
  repo: github.com
  org: ch007m
  name: quarkus-app-rhdh-2

image:
  url: quay.io/ch007m/my-quarkus-app
  registry:  # NOT USED
  organization:  # NOT USED
  name:  # NOT USED